ServerName localhost
ServerTokens Prod
ServerSignature Off
<Directory /var/www/html>
    Options -Indexes
    AllowOverride None
    DirectoryIndex index.php
    Require all granted
    LimitRequestBody 1048576
</Directory>
